In [1]:
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
from sklearn.datasets import load_iris
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split


#data =load_iris()



iris=load_iris()
x=iris.data
y=iris.target

#x_train,x_test,y_train,y_test=train_test_split(data.data,data.target,test_size=0.4,random_state=5)
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.4,random_state=5)
model=KNeighborsClassifier(n_neighbors=5)
model.fit(x_train,y_train)
y_pred=model.predict(x_test)

print("Acuraccy of KNN\t\t\t\t",accuracy_score(y_pred,y_test))

pd.DataFrame({'actual':y_test,'predction':y_pred,'correct classification':(y_test==y_pred)})

Acuraccy of KNN				 0.9666666666666667

    actual  predction  correct classification
0        1          1                    True
1        2          2                    True
2        2          2                    True
3        0          0                    True
4        2          2                    True
5        1          1                    True
6        0          0                    True
7        1          1                    True
8        0          0                    True
9        1          1                    True
10       1          1                    True
11       2          1                   False
12       2          2                    True
13       2          2                    True
14       0          0                    True
15       0          0                    True
16       2          2                    True
17       2          2                    True
18       0          0                    True
19       0          0                    True
20       1          1                    True
21       2          2                    True
22       0          0                    True
23       1          1                    True
24       1          1                    True
25       2          2                    True
26       1          1                    True
27       1          1                    True
28       1          1                    True
29       2          2                    True
30       0          0                    True
31       1          1                    True
32       1          1                    True
33       0          0                    True
34       1          1                    True
35       0          0                    True
36       0          0                    True
37       2          2                    True
38       0          0                    True
39       2          2                    True
40       2          2                    True
41       1          1                    True
42       0          0                    True
43       0          0                    True
44       1          1                    True
45       2          1                   False
46       1          1                    True
47       2          2                    True
48       2          2                    True
49       0          0                    True
50       2          2                    True
51       0          0                    True
52       0          0                    True
53       0          0                    True
54       0          0                    True
55       1          1                    True
56       1          1                    True
57       1          1                    True
58       1          1                    True
59       2          2                    True

In [2]:
count = 0
for i in range(len(y_pred)):
    if(y_pred[i]!=y_test[i]):
        count=count+1
print(count)

2